# docker-compose.yml
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_service
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11000:11434"
    restart: unless-stopped
    networks:
      - ollama_network
      - trip-crawler_app_network

  django_app:
    build: .
    container_name: django_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_NAME=scraping_db
      - DB_USER=aa_nadim
      - DB_PASSWORD=aa_nadim123
      - DB_HOST=postgres
      - DB_PORT=5432
      - OLLAMA_BASE_URL=http://ollama:11434/api/generate
    networks:
      - ollama_network
      - trip-crawler_app_network
    depends_on:
      - ollama
    working_dir: /app
    command: >
      sh -c "
        sleep 30 &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "

volumes:
  ollama_data:

networks:
  ollama_network:
    driver: bridge
  trip-crawler_app_network:
    external: true